#!/usr/bin/env node
const readline = require("readline/promises");
const { stdin, stdout } = require("process");
const fs = require("fs");
const path = require("path");
const os = require("os");
const { execSync } = require("child_process");

const rl = readline.createInterface({ input: stdin, output: stdout });

async function ask(question, { required = true, defaultValue } = {}) {
  const suffix = defaultValue ? ` (${defaultValue}): ` : ": ";
  while (true) {
    const answer = (await rl.question(question + suffix)).trim();
    if (answer) return answer;
    if (defaultValue !== undefined) return defaultValue;
    if (!required) return "";
    console.log("  This one's required — let's try again.");
  }
}

async function askYesNo(question, defaultYes = true) {
  const hint = defaultYes ? "Y/n" : "y/N";
  const answer = (await rl.question(`${question} (${hint}): `)).trim().toLowerCase();
  if (!answer) return defaultYes;
  return answer.startsWith("y");
}

function writeEnvFile(values, projectDir) {
  const content = `# Generated by setup.js — see README.md for how to edit this by hand later.
GITHUB_TOKEN=${values.token}
SLACK_WEBHOOK_URL=${values.webhook}
REPO_LIST=${values.repoList}
THRESHOLD_HOURS=${values.threshold}
`;
  fs.writeFileSync(path.join(projectDir, ".env"), content);
}

function setupSystemd(values, projectDir) {
  const home = os.homedir();
  const systemdDir = path.join(home, ".config", "systemd", "user");
  fs.mkdirSync(systemdDir, { recursive: true });

  const nodePath = process.execPath; // the exact node binary currently running this script
  const envPath = path.join(projectDir, ".env");

  const serviceContent = `[Unit]
Description=PR Reminder Bot

[Service]
Type=oneshot
WorkingDirectory=${projectDir}
EnvironmentFile=${envPath}
ExecStart=${nodePath} run.js
`;

  const timerContent = `[Unit]
Description=Run PR Reminder Bot every hour

[Timer]
OnBootSec=5min
OnUnitActiveSec=1h

[Install]
WantedBy=timers.target
`;

  fs.writeFileSync(path.join(systemdDir, "pr-reminder.service"), serviceContent);
  fs.writeFileSync(path.join(systemdDir, "pr-reminder.timer"), timerContent);

  execSync("systemctl --user daemon-reload", { stdio: "inherit" });
  execSync("systemctl --user enable --now pr-reminder.timer", { stdio: "inherit" });

  console.log("\n✅ systemd timer installed and running — it'll check every hour from now on.");
  console.log("   View logs any time with: journalctl --user -u pr-reminder.service -n 20 --no-pager");
}

async function main() {
  console.log("PR Reminder Bot — setup\n");
  console.log("This will ask for your GitHub token, Slack webhook, and which repos to watch,");
  console.log("then write your .env file and optionally set up automatic scheduling.\n");

  const token = await ask(
    "GitHub token (Settings > Developer settings > Fine-grained tokens, Pull requests: Read-only)"
  );
  const webhook = await ask(
    "Slack Incoming Webhook URL (api.slack.com/apps > your app > Incoming Webhooks)"
  );
  const repoList = await ask(
    "Repo(s) to watch, comma-separated as owner/repo",
    { defaultValue: "" }
  );
  const threshold = await ask(
    "Hours before a PR counts as stale",
    { defaultValue: "24" }
  );

  const projectDir = __dirname;
  writeEnvFile({ token, webhook, repoList, threshold }, projectDir);
  console.log(`\n✅ Wrote .env to ${path.join(projectDir, ".env")}`);

  console.log("\nRunning a test check now...\n");
  try {
    execSync(`node ${path.join(projectDir, "run.js")}`, {
      stdio: "inherit",
      env: { ...process.env, GITHUB_TOKEN: token, SLACK_WEBHOOK_URL: webhook, REPO_LIST: repoList, THRESHOLD_HOURS: threshold },
    });
  } catch (err) {
    console.log("\n⚠️  The test run hit an error above — check your token/webhook/repo values and try `node run.js` manually.");
  }

  if (process.platform === "linux") {
    const hasSystemd = (() => {
      try {
        execSync("systemctl --user --version", { stdio: "ignore" });
        return true;
      } catch {
        return false;
      }
    })();

    if (hasSystemd) {
      const wantsAutomation = await askYesNo(
        "\nSet this up to run automatically every hour via systemd?"
      );
      if (wantsAutomation) {
        setupSystemd({ token, webhook, repoList, threshold }, projectDir);
      } else {
        console.log("\nSkipped. You can run `node run.js` manually any time, or set up scheduling later — see README.md.");
      }
    } else {
      console.log("\nsystemd not detected — see README.md for cron or other scheduling options.");
    }
  } else {
    console.log("\nAutomatic scheduling setup here only supports Linux/systemd for now — see README.md for cron (macOS) or other options.");
  }

  console.log("\nDone. 🎉");
  rl.close();
}

main();
